### PR TITLE
SOAP web service for getting basic game(s) information all done.

### PR DESCRIPTION
**Pull request by andresdsep**
Dependent on current DataAccess and DataSets, as well as their connection settings... can't be deployed until those are changed to deployment settings.

### CODE REVIEW

**Comment by loklaan** [comment]
I'll read the code later, but for the time being it could be worth looking into [various MSBuild options](http://msdn.microsoft.com/en-us/library/dd393574%28v=vs.110%29.aspx). I'm sure there is somehow a way to pump out two artifacts.

**Comment by loklaan** [comment]
I read the notion mentioned a few times in AppVeyor docs.

**Comment by andresdsep** [comment]
What do you mean by "pump out two artifacts"?

**Comment by loklaan** [comment]
I can't reference MSBuild, but I imagine this to be possible. Examples of what I mean:
1. MSBuild contains 2 'targets'.
   - Normal one, like we currently have. Includes everything.
   - Additional one that only builds the SOAP services and deps.
2. When you hit build in VS or push code for AppVeyor to gobble up, it creates to different bin folders. Something _like_:
   - The whole projects builds into `Debug/WebApp.exe` & `Release/WebApp.exe` on the first target
   - The additional target builds into `Debug_Package/SOAPServ.exe` & `Release_Package/SOAPServ.exe`
3. The SOAP service target uses different connection strings & sql stored procedures. MSBuild can reference different elements from the DataAccess config.

**Comment by loklaan** [comment]
Looks good to me. Have not tested it myself though sorry

**Pull request merged**
